service
  - type: web
    name: solDataMap
    env: python
    plan: free
    rootDir: SolomonIslandsDataMap
    # Pull files from setting.ini
    buildCommand: "Build Command = pip install --upgrade pip setuptools wheel && pip install -U nbdev && pip install -r requirements.txt && pip pip install -e \".[dev]\""
    # Run the correct ptyhon file
    startCommand: "gunicorn --chdir src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
