# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SolomonIslandsDataMap',
                'doc_host': 'https://Gippers.github.io',
                'git_url': 'https://github.com/Gippers/SolomonIslandsDataMap',
                'lib_path': 'SolomonIslandsDataMap'},
  'syms': { 'SolomonIslandsDataMap.load_data': { 'SolomonIslandsDataMap.load_data.SolomonCensus': ( 'gen_map.html#solomoncensus',
                                                                                                    'SolomonIslandsDataMap/load_data.py'),
                                                 'SolomonIslandsDataMap.load_data.SolomonCensus.__init__': ( 'gen_map.html#solomoncensus.__init__',
                                                                                                             'SolomonIslandsDataMap/load_data.py'),
                                                 'SolomonIslandsDataMap.load_data.SolomonCensus.elt': ( 'gen_map.html#solomoncensus.elt',
                                                                                                        'SolomonIslandsDataMap/load_data.py'),
                                                 'SolomonIslandsDataMap.load_data.SolomonGeo': ( 'gen_map.html#solomongeo',
                                                                                                 'SolomonIslandsDataMap/load_data.py'),
                                                 'SolomonIslandsDataMap.load_data.SolomonGeo.__init__': ( 'gen_map.html#solomongeo.__init__',
                                                                                                          'SolomonIslandsDataMap/load_data.py'),
                                                 'SolomonIslandsDataMap.load_data.SolomonGeo.elt': ( 'gen_map.html#solomongeo.elt',
                                                                                                     'SolomonIslandsDataMap/load_data.py')}}}
