# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SolomonIslandsDataMap',
                'doc_host': 'https://Gippers.github.io',
                'git_url': 'https://github.com/Gippers/SolomonIslandsDataMap',
                'lib_path': 'SolomonIslandsDataMap'},
  'syms': {'SolomonIslandsDataMap.core': {'SolomonIslandsDataMap.core.foo': ('core.html#foo', 'SolomonIslandsDataMap/core.py')}}}
