# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_gen_map.ipynb.

# %% auto 0
__all__ = ['app', 'mytitle', 'mygraph', 'aggs', 'dropdown']

# %% ../nbs/01_gen_map.ipynb 2
from nbdev.showdoc import *
from .load_data import *
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio # Unless this is used graphs will not be dynamic?
import json
import pandas as pd
import numpy as np
from fastcore.test import *
from dash import Dash, dcc, Output, Input  # pip install dash
import dash_bootstrap_components as dbc    # pip install dash-bootstrap-components

# %% ../nbs/01_gen_map.ipynb 6
# Build your components
app = Dash(__name__, external_stylesheets=[dbc.themes.VAPOR])
mytitle = dcc.Markdown(children='# Solomon Islands Data Map')
mygraph = dcc.Graph(figure={})
aggs = geo_df.loc[:, 'agg'].unique()
dropdown = dcc.Dropdown(options=aggs,
                        value=aggs[0],  # initial value displayed when page first loads
                        clearable=False)

# %% ../nbs/01_gen_map.ipynb 8
app.layout = dbc.Container([mytitle, mygraph, dropdown])
