# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_load_data.ipynb.

# %% auto 0
__all__ = ['SolomonGeo', 'SolomonCensus']

# %% ../nbs/00_load_data.ipynb 2
from nbdev.showdoc import *
import geopandas as gp
import pandas as pd
from git import Repo
import json

# %% ../nbs/00_load_data.ipynb 5
class SolomonGeo:
    # TODO work out how to format this?
    # Look at nbdev docs maybe?
    '''
    Load the solomon islands geography data 
    Attributes:
        adm3    Geopandas dataframe containing admin 3 geographies.
    '''
    def __init__(self):
        repo = Repo('.', search_parent_directories=True)
        fp = str(repo.working_tree_dir) + "/testData/"
        self.adm3 = self.elt(fp)

    def elt(self, pw:str, # The pathway to the dataset
           )-> gp.GeoDataFrame: # The geojason dataset for given aggregation
        '''
        Load and transform given filepath into a geejason geopandas dataframe
        '''
        adm3 = gp.read_file(pw + '2009_PHC_Solomons_Ward_4326')
        #adm3.to_file('myJson.geojson', driver='GeoJSON')
        # Need to set the index, currently using WID
        adm3 = adm3.set_index(adm3["WID"].values)
        return adm3

    def get_geojson(self,) -> dict: # Geo JSON formatted dataset
        '''
        A getter method for geography as a Geo JSON
        '''
        return json.loads(self.adm3.to_json())


# %% ../nbs/00_load_data.ipynb 9
class SolomonCensus:
    '''
    Load the solomon islands census data 
    '''
    def __init__(self):
        repo = Repo('.', search_parent_directories=True)
        fp = str(repo.working_tree_dir) + "/testData/"
        self.data = self.elt(fp)

    def elt(self, pw:str, # The pathway to the dataset
           )-> pd.pandas: # Return the pandas dataset
        '''
        Load and transform data from filepath into pandas dataset
        '''
        df = pd.read_csv(pw + 'sol_census_2009_ward.csv')
        df['id'] = df['id'].apply(str)  # Change type of id
        # TODO load all the files and merge them together?
        return df



