# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_load_data.ipynb.

# %% auto 0
__all__ = ['SolomonGeo']

# %% ../nbs/00_load_data.ipynb 2
from nbdev.showdoc import *
import geopandas, pandas
from git import Repo

# %% ../nbs/00_load_data.ipynb 4
class SolomonGeo:
    '''
    Load the solomon islands geographies
    '''
    def __init__(self):
        repo = Repo('.', search_parent_directories=True)
        fp = str(repo.working_tree_dir) + "/testData/"
        adm3 = geopandas.read_file('zip://' +fp + 'slb_admbnda_adm3.zip')
        adm3.to_file('myJson.geojson', driver='GeoJSON')

        # 
        self.adm3 = adm3
    # TODO create functions to return 
