# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_table_page.ipynb.

# %% auto 0
__all__ = ['mytitle', 'layout']

# %% ../../nbs/04_table_page.ipynb 2
# TODO minimise these imports a bit where possible
from nbdev.showdoc import *
# TODO work out how to get around below hack
try:
    from SolomonIslandsDataMap.dash_components import gen_dash_table, gen_dd
    from SolomonIslandsDataMap.app_data import mytitle, data_table, stored_data, dropdown_location \
        , control_type, dd_var, dd_measure, dropdown_geo
    from SolomonIslandsDataMap.load_data import SolomonGeo
except: 
    from dash_components import gen_dash_table, gen_dd
    from app_data import mytitle, map_graph, selectedBarGraph, stored_data, dropdown_location \
        , control_type, dd_var, dd_measure, dropdown_geo
    from load_data import SolomonGeo
from fastcore.test import *
from dash import Dash, dcc, Output, Input, State, html, Patch, ctx, register_page  
import dash_bootstrap_components as dbc    

# %% ../../nbs/04_table_page.ipynb 3
try:
    register_page(__name__, 
                        path='/datatable',
                        title='Data Table',
                        name='Data Table')
except:
    pass

# %% ../../nbs/04_table_page.ipynb 6
mytitle = dcc.Markdown(children="## This is a placeholder test!!") # TODO This needs a default title

# %% ../../nbs/04_table_page.ipynb 7
def layout():
    return dbc.Container([mytitle,
                          data_table,
                        ])
