name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    name: 'Create env file'
        run: |
          touch .env
          echo ACCESS_KEY=${{ secrets.ACCESS_KEY }} >> .env
          echo SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} >> .env
          echo REGION_NAME=${{ secrets.REGION_NAME }} >> .env
          cat .env
    [uses: fastai/workflows/quarto-ghp@master]
