name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: gippers/SolomonIslandsDataMap/actions/nbdev-ci@main] # https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions
