name: Deploy to GitHub Pages
on:
  push:
    branches: [master, main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        env: # This passes enivronment variables which are accessed using os.environ['ENV_NAME']
          ACCESS_KEY:  ${{ secrets.ACCESS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}   
          REGION_NAME: ${{ secrets.REGION_NAME }}
        with:
          github_token: ${{ secrets.PAT }}
          branch: refs/pull/42/merge
          directory: .