name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: fastai/workflows/nbdev-ci@master
      env: # This passes enivronment variables which are accessed using os.environ['ENV_NAME']
        ACCESS_KEY:  ${{ secrets.ACCESS_KEY }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}   
        REGION_NAME: ${{ secrets.REGION_NAME }}